### ISSUE TITLE
Artist image 127 is missing

### ISSUE THREAD

**Issue by kingsukhoi** [mru-comp3512-archive/f2018-assign2#1]
Image for Jacob van Ruisdael(artist id 127) is missing from both full and square folder.

**Comment by AttitudeFever** [comment]
I have mentioned that in class but was more taken as a joke, so to fix it
on my end I have created duplicated that image of artist 131 (full and
square) for artist 127 (its missing person image) many artists has this
image if they don't have actual image... so why not artist 127, so its
fixed that way.

**Comment by rconnolly** [comment]
Thanks for letting me know ... I fixed the problem as you suggested
